server:
  port: 30105

# spring 配置
spring:
  application:
    name: alinesno-infra-base-storage-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_alinesno_infra_base_storage_v100?serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: adminer
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
  devtools:
    restart:
      enabled: true
  servlet:
    multipart.resolve-lazily: true

actable:
  table:
    auto: update
  model:
    pack: > 
      com.alinesno.infra.base.storage.entity;
      com.alinesno.infra.base.storage.plugins.entity
  database:
    type: mysql
  index:
    prefix: alinesno_base_storage_idx_
  unique:
    prefix: alinesno_base_storage_uni_

# sa-token配置
sa-token:
  token-name: satoken
  host-path: http://alinesno-infra-base-identity-auth-application.beta.base.infra.linesno.com
  sso:
    auth-url: ${sa-token.host-path}/login
    is-http: true
    check-ticket-url: ${sa-token.host-path}/sso/checkTicket
    slo-url: ${sa-token.host-path}/sso/signout
    get-data-url: ${sa-token.host-path}/sso/getData
  sign:
    secret-key:

dromara:
  x-file-storage: #文件存储配置
    default-platform: qiniu-kodo #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    local-plus:
      - platform: local # 存储平台标识
        enable-storage: true  #启用存储
        enable-access: true #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: http://127.0.0.1:${server.port}/local-plus/ # 访问域名，例如：“http://127.0.0.1:8030/local-plus/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: local-plus/ # 基础路径
        path-patterns: /local-plus/** # 访问路径
        storage-path: ${user.home}/alinesno-upload-files/ # 存储路径
    minio:
      - platform: minio # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ${alinesno.infra.minio.access-key}
        secret-key: ${alinesno.infra.minio.secret-key}
        end-point: ${alinesno.infra.minio.bucket}
        bucket-name: ${alinesno.infra.minio.bucket}
        domain: ${alinesno.infra.minio.domain} # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: test/ # 基础路径
    qiniu-kodo:
      - platform: qiniu-kodo # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ${alinesno.infra.qiniu.access-key}
        secret-key: ${alinesno.infra.qiniu.secret-key}
        bucket-name: ${alinesno.infra.qiniu.bucket}
        domain:  ${alinesno.infra.qiniu.domain} # 访问域名，注意“/”结尾，例如：http://abc.hn-bkt.clouddn.com/
        base-path: base/ # 基础路径
      - platform: qiniu-kodo-pub # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ${alinesno.infra.qiniu.access-key}
        secret-key: ${alinesno.infra.qiniu.secret-key}
        bucket-name: ${alinesno.infra.qiniu.bucket-pub}
        domain:  ${alinesno.infra.qiniu.domain-pub} # 访问域名，注意“/”结尾，例如：http://abc.hn-bkt.clouddn.com/
        base-path: public/ # 基础路径
    aliyun-oss:
      - platform: aliyun-oss-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ??
        secret-key: ??
        end-point: ??
        bucket-name: ??
        domain: ?? # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: test/ # 基础路径
