-- 这里使用的是 mysql
CREATE TABLE `file_detail`
(
    `id`                varchar(32)  NOT NULL COMMENT '文件id',
    `url`               varchar(512) NOT NULL COMMENT '文件访问地址',
    `size`              bigint(20)   DEFAULT NULL COMMENT '文件大小，单位字节',
    `filename`          varchar(256) DEFAULT NULL COMMENT '文件名称',
    `original_filename` varchar(256) DEFAULT NULL COMMENT '原始文件名',
    `base_path`         varchar(256) DEFAULT NULL COMMENT '基础存储路径',
    `path`              varchar(256) DEFAULT NULL COMMENT '存储路径',
    `ext`               varchar(32)  DEFAULT NULL COMMENT '文件扩展名',
    `content_type`      varchar(128)  DEFAULT NULL COMMENT 'MIME类型',
    `platform`          varchar(32)  DEFAULT NULL COMMENT '存储平台',
    `th_url`            varchar(512) DEFAULT NULL COMMENT '缩略图访问路径',
    `th_filename`       varchar(256) DEFAULT NULL COMMENT '缩略图名称',
    `th_size`           bigint(20)   DEFAULT NULL COMMENT '缩略图大小，单位字节',
    `th_content_type`   varchar(128)  DEFAULT NULL COMMENT '缩略图MIME类型',
    `object_id`         varchar(32)  DEFAULT NULL COMMENT '文件所属对象id',
    `object_type`       varchar(32)  DEFAULT NULL COMMENT '文件所属对象类型，例如用户头像，评价图片',
    `attr`              text COMMENT '附加属性',
    `file_acl`          varchar(32)  DEFAULT NULL COMMENT '文件ACL',
    `th_file_acl`       varchar(32)  DEFAULT NULL COMMENT '缩略图文件ACL',
    `create_time`       datetime     DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8 ROW_FORMAT = DYNAMIC COMMENT ='文件记录表';


CREATE TABLE `storage_application` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `application_code` VARCHAR(255) DEFAULT NULL COMMENT '应用代码',
  `token` VARCHAR(255) DEFAULT NULL COMMENT '应用值',
  `max_file_size` INT DEFAULT NULL COMMENT '最大文件长度',
  `file_type` VARCHAR(255) DEFAULT NULL COMMENT '文件类型',
  `api_key` VARCHAR(255) DEFAULT NULL COMMENT '接口密钥',
  `max_upload_count` INT DEFAULT NULL COMMENT '最大上传次数',
  `max_download_count` INT DEFAULT NULL COMMENT '最大下载次数',
  `banner` VARCHAR(255) DEFAULT NULL COMMENT '应用logo标识',
  `company_name` VARCHAR(255) DEFAULT NULL COMMENT '公司名称',
  `channel_ids` VARCHAR(255) DEFAULT NULL COMMENT '所开通渠道',
  `app_code` VARCHAR(255) DEFAULT NULL COMMENT '应用码',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='存储应用实体类';


CREATE TABLE `storage_file` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `file_ext` VARCHAR(255) COMMENT '文件扩展名',
  `file_flag` VARCHAR(255) COMMENT '文件标识',
  `file_name` VARCHAR(255) COMMENT '文件名称',
  `file_size` BIGINT(20) COMMENT '文件长度',
  `file_url` VARCHAR(255) COMMENT '地址链接',
  `is_public` VARCHAR(255) COMMENT '是否公开',
  `save_type` VARCHAR(255) COMMENT '保存类型',
  `api_key` VARCHAR(255) COMMENT '接口密钥',
  `originalFilename` VARCHAR(255) COMMENT '原始文件名',
  `basePath` VARCHAR(255) COMMENT '基础路径',
  `path` VARCHAR(255) COMMENT '路径',
  `ext` VARCHAR(255) COMMENT '扩展名',
  `contentType` VARCHAR(255) COMMENT '内容类型',
  `platform` VARCHAR(255) COMMENT '平台',
  `thUrl` VARCHAR(255) COMMENT '缩略图URL',
  `thFilename` VARCHAR(255) COMMENT '缩略图文件名',
  `thSize` BIGINT(20) COMMENT '缩略图大小',
  `thContentType` VARCHAR(255) COMMENT '缩略图内容类型',
  `objectId` VARCHAR(255) COMMENT '对象ID',
  `objectType` VARCHAR(255) COMMENT '对象类型',
  `attr` VARCHAR(255) COMMENT '属性',
  `fileAcl` JSON COMMENT '文件ACL',
  `thFileAcl` JSON COMMENT '缩略图文件ACL',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='存储文件实体类';


CREATE TABLE `storage_file_history` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `file_ext` VARCHAR(255) COMMENT '文件扩展名',
  `file_flag` VARCHAR(255) COMMENT '文件标识',
  `file_name` VARCHAR(255) COMMENT '文件名称',
  `file_size` BIGINT(20) COMMENT '文件长度',
  `file_url` VARCHAR(255) COMMENT '地址链接',
  `is_public` VARCHAR(255) COMMENT '是否公开',
  `save_type` VARCHAR(255) COMMENT '保存类型',
  `api_key` VARCHAR(255) COMMENT '接口密钥',
  `originalFilename` VARCHAR(255) COMMENT '原始文件名',
  `basePath` VARCHAR(255) COMMENT '基础路径',
  `path` VARCHAR(255) COMMENT '路径',
  `ext` VARCHAR(255) COMMENT '文件扩展名',
  `contentType` VARCHAR(255) COMMENT '内容类型',
  `platform` VARCHAR(255) COMMENT '平台',
  `thUrl` VARCHAR(255) COMMENT '缩略图URL',
  `thFilename` VARCHAR(255) COMMENT '缩略图文件名',
  `thSize` BIGINT(20) COMMENT '缩略图大小',
  `thContentType` VARCHAR(255) COMMENT '缩略图内容类型',
  `objectId` VARCHAR(255) COMMENT '对象ID',
  `objectType` VARCHAR(255) COMMENT '对象类型',
  `attr` JSON COMMENT '属性',
  `fileAcl` JSON COMMENT '文件ACL',
  `thFileAcl` JSON COMMENT '缩略图文件ACL',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='存储文件实体类';


CREATE TABLE `storage_requests` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `request_url` VARCHAR(255) COMMENT '请求路径',
  `storage_url` VARCHAR(255) COMMENT '保存路径',
  `request_application` VARCHAR(255) COMMENT '请求应用',
  `agent` VARCHAR(255) COMMENT '请求信息',
  `filename` VARCHAR(255) COMMENT '文件名称',
  `request_ip` VARCHAR(255) COMMENT '请求IP',
  `response_time` BIGINT COMMENT '响应时间',
  `request_user_id` VARCHAR(255) COMMENT '请求用户',
  `request_type` VARCHAR(255) COMMENT '文件类型',
  `request_username` VARCHAR(255) COMMENT '请求用户名',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` VARCHAR(255) COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` BIGINT COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='存储请求记录实体类';
